### ISSUE TITLE
Gelsight sensor broke

### ISSUE THREAD

**Issue by mariabauza** [mcubelab/rgrasp#36] opened 2017-11-17 15:13 UTC
@OleguerCanal @mariabauza

The gelsight sensor broke this morning during data collection. The plastic spatula craked and must be replaced.

**Comment by albertor** [comment] 2017-11-17 17:23
Oh, boy.
@mariabauza @OleguerCanal @fhogan @EZas456

It'd be great if you can write a log of when and how these "break" events happen. In the long run, it could be assess if there are improvements that we could do to the grasp policy or to the hardware to prevent them.

**Comment by fhogan** [comment] 2017-11-17 17:36
@albertor 

Thanks for the suggestion. I opened issue #37 where we can start tracking gelsight problems.

**Comment by albertor** [comment] 2017-11-17 17:39
Cool.
@mariabauza @OleguerCanal @fhogan
Might also want to ask Elliott if he would benefit from any specific information in the log. Maybe he wants to write more details about what broke or adding a picture.

**Comment by EZas456** [comment] 2017-11-17 18:04
There are lots of ways they can break so a picture or description of what
the problem is would be useful ("gelsight isn't working" is not that
informative).
It seems to be a mixture of hardware and grasp policy and a lot of the
hardware problems we're seeing are being addressed in the new version.

**Closed as completed** 2017-11-22 23:29 UTC
